name: Crawl Mongolia News

on:
  schedule:
    - cron: "0 4,11 * * *"   # 每天12:00 和 19:00（本地时间）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        run: python crawler.py

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add news.json

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "update news data"
            git push origin HEAD:main
          fi
